services:
  app:
    image: ghcr.io/eudaldca/partage:latest
    container_name: partage_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ${LARAVEL_STORAGE}:/var/www/html/storage
      - ${NGINX_CONFIG}:/etc/nginx/conf.d/default.conf:ro
      - ${SUPERVISOR_CONFIG}:/etc/supervisor/conf.d/
    ports:
      - ${WEB_PORT}:80
    environment:
      - UID=${UID:-1000}
      - GID=${GID:-1000}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - partage_network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  queue:
    image: ghcr.io/eudaldca/partage:latest
    container_name: partage_queue
    restart: unless-stopped
    working_dir: /var/www/html
    command: php artisan queue:work --tries=3 --timeout=90
    volumes:
      - ${LARAVEL_STORAGE}:/var/www/html/storage
    environment:
      - UID=${UID:-1000}
      - GID=${GID:-1000}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - partage_network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: mariadb:10.11
    container_name: partage_db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${DB_STORAGE}:/var/lib/mysql
    networks:
      - partage_network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:8.2-alpine
    container_name: partage_redis
    restart: unless-stopped
    volumes:
      - ${REDIS_STORAGE}:/data
    networks:
      - partage_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  partage_network:
    driver: bridge
